[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['cd backend && npm ci --only=production']

[phases.start]
cmd = 'cd backend && node server.js'